name: Deploy Backend to Azure Container Apps

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t backend-app:latest ./backend

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image to ACR
        run: |
          docker tag backend-app:latest ${{ secrets.ACR_LOGIN_SERVER }}/backend-app:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend-app:latest

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name backend-app \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/backend-app:latest