name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Récupération du code
      - uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io

      # Build et push de l'image Docker avec un tag basé sur la date/heure
      - name: Build and push Docker image
        run: |
          TAG=$(date +'%Y%m%d-%H%M%S')
          echo "Using tag: $TAG"

          # Build avec le tag horodaté
          docker build -f frontend/Dockerfile -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/audiomancy-front:$TAG frontend/

          # Push du tag horodaté
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/audiomancy-front:$TAG