name: Build and Push Docker Image to Azure Container Registry

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - uses: actions/checkout@v4

      # Se connecter à Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t audiomancy-front:latest .

      # Se connecter au registre Azure Container Registry
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Tag et push de l'image
      - name: Tag and Push Docker image
        run: |
          docker tag audiomancy-front:latest ${{ secrets.ACR_REGISTRY }}/audiomancy-front:latest
          docker push ${{ secrets.ACR_REGISTRY }}/audiomancy-front:latest
